[build-sytem]
required = ["setuptools>=68", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "valet"
authors = [
    {name = "Dennis Snell", email = "dmsnell@xkq.io"}
]
readme = "README.md"
requires-python = ">=3.12, < 3.13"
dynamic = ["version"]
dependencies = [
    "openai-whisper"
]

[tool.setuptools_scm]

[project.scripts]
valet-gui = "valet.gui.valet_app:run_valet_app"
valet = "valet.cli.valet_cli:main"